# Mean

In [2]:
import numpy as np
import math
x = np.array([1,3,5,6])
mean_x = np.mean(x)
print(mean_x)
# in case the data contains Nan values
x_nan = np.array([1,math.nan,math.nan,3,5,6, math.nan])
mean_x_nan = np.nanmean(x_nan)
print(mean_x_nan, np.mean(x_nan))

3.75
3.75 nan


# variance

In [3]:
x = np.array([1,3,5,6])
variance_x = np.var(x)

# here you need to specify the degrees of freedom (df) max number of logically independent data points that have freedom to vary
x_nan = np.array([1,3,5,6, math.nan])
var_x_nan = np.nanvar(x_nan, ddof = 0)
print(variance_x,var_x_nan, np.var(x_nan, ddof = 1))

3.6875 3.6875 nan


In [4]:
l = 3
print(np.nanvar(x_nan, ddof=l))
print(np.nanvar(x_nan, ddof=0)*(4/(4-l)))
print(np.var(x, ddof=l))

14.75
14.75
14.75


# standard deviation
![Standard Deviation Equation](https://latex.codecogs.com/svg.image?\Large&space;\sigma=\sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i-\mu)^2})

In [5]:
x = np.array([1,3,5,6])
std_x = np.std(x)

x_nan = np.array([1,3,5,6, math.nan])
# eclude nan values

std_x_nan = np.nanstd(x_nan)
print(std_x, std_x_nan)

1.920286436967152 1.920286436967152


In [6]:
filterd_x = x_nan[~np.isnan(x_nan)]
print(filterd_x)

[1. 3. 5. 6.]


# Covariance

In [7]:
x = np.array([1,3,5,6,2])
y = np.array([-2,-4,-5,-6,3])
#this will return the covariance matrix of x,y containing x_variance, y_variance on diagonal elements and covariance of x,y
cov_xy = np.cov(x,y)
print(cov_xy)

[[ 4.3  -5.35]
 [-5.35 12.7 ]]


# Correlation

In [9]:
x = np.array([1,3,5,6])
y = np.array([-2,-4,-5,-6])
corr = np.corrcoef(x,y)
print(corr)

[[ 1.         -0.99026741]
 [-0.99026741  1.        ]]
